name = "ai-service"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 环境变量（在 Cloudflare Dashboard 中设置实际值）
[env.production.vars]
# DEEPSEEK_API_KEY = "your-deepseek-api-key"  # 使用 wrangler secret 设置
# ALLOWED_ORIGINS = "https://yourdomain.com,https://localhost:3000"

# 开发环境配置
[env.development]
name = "ai-service-dev"

# KV 存储（可选，用于缓存或会话管理）
# [[kv_namespaces]]
# binding = "CHAT_SESSIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# R2 存储（可选，用于文件存储）
# [[r2_buckets]]
# binding = "AI_FILES"
# bucket_name = "ai-service-files"

# 添加自定义域名
[[routes]]
pattern = "api.lcif2025.cc/*"
zone_name = "lcif2025.cc"
